# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UsjWwgUf7fqJEkcI2TorC4QfqqlynBtl7f3Ge7bsja8y8nDose7YCxmefyBiJj1l7feV3CPOiq+MB1AHPbByDxZ8r6zY4JRxjZe+a+IMh6yC4yH0t/hxqDMnDp9HEaWNlsAJjc2EcjoDDAq6Ue3NswuB/WsUReoX22WvAWplZA4uF0IYlMZb4bK+ykp98xy5aWxEugyMpjCZ5HhMYc2eOpOupzL0vimlEpF0BlrbcRetIW5xthJD32n6M038K9EKRG3Wzt3/IXFyVqh8wPUEubfsRniXWzTuY1ZoNZQVS8m+fM+r0SubWcVUiUCLjvAk4ILKnLGa5pZtLHRBmxLGKNmh//J8F4jEyZFbbONv5WYj0gsQQVjq0phZk3Hn9SMI291QkKcgbTd9NPxgF3XpO09kJgU0BkkHLAa0FjcR82FyW9/Lv2r7EmQPmejk4X0/XPsFSg2RZwI6i2/pZPKX1RoVtZUYnknN0lqCFIcVutSn8vvveVQgXNLJ+H0BQmOQem++HYp7AOPPlBdzZYTcsO3UM3M8BAu3XVwYnuI9CwwRQSZzNWBc+fH62mNKRsS0PZr6fy3qDBx/BqeoMVgBrUXGB0PoBznIwzMOnfUXd+X5W0O6+5n+AJY8qCa4Qv/zlH2HyAYxRHxAo4LFAFrPRHWToeX8fiqfvX9JLDvDkYA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
