travis:
  secure:
    BINSTAR_TOKEN: 1KuAtupCjB11KioB4CfSM8nEE4NrIaowxbIt5pT2hELgYonAiioJnggtutDl4/mZm450nIOYFbb7CrxiA5eILe9iHXi2peCb91eeUr1PkeevflyozkX61aqhdp5LBfu/m2b8f8+gqyQQJyuhgNlmkApcl8l1sl2Grot+sQSintF46HVCtoYCkQggBzHq+ofhERquD5a3vYOuJrte68m7wjC1F2sBfTJsYvHGTewOe7i7M9GnHhugtfma+5WK57glxxkY19bGyKLgr/kWR+pM4gyZ7JZm2ySa65KO6l8JzrnTF/pBj7I8BAQ7OcYxE2+065u0a6iilvDOmN9qT5je6pQ69625rfxnoloEJq5kSl77m6X5TAvxBq8Mz/YEcUpve+F76k6EkMTGdpHGDIJuzdrR41vbf1O8ue7cEplsBiFXtrGpbHCrcGVwFKB/ke+sycWm4ScxZfCs/GWv//ZnS99Y8xfB/qGTWXI23e0S+FqwLXu99wsXmQIhNCPeNzCU0QcQIi2oT3F+18iqA6UYilrHv2jRWsATJsJRVUAhySskMn2xaO8S1BjSuLaerDtgb6GE8J+RPzYERCERPvscmZjx/Azwp3HxyUOsX8e6eQts4EqeWSCFYpKvcrYWqY+xzLAGLKDOVG95GJ5NVAHqTP4MzXZ2cUZAkSNNxwG/FV0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
